// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// unit
Rcpp::List unit(arma::vec eigd, arma::mat U, arma::mat An, double lambda, Rcpp::Nullable<arma::mat> Z0, Rcpp::Nullable<arma::mat> V0, double err, int maxIter, double rho);
RcppExport SEXP _PIE_unit(SEXP eigdSEXP, SEXP USEXP, SEXP AnSEXP, SEXP lambdaSEXP, SEXP Z0SEXP, SEXP V0SEXP, SEXP errSEXP, SEXP maxIterSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type eigd(eigdSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type U(USEXP);
    Rcpp::traits::input_parameter< arma::mat >::type An(AnSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type Z0(Z0SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type V0(V0SEXP);
    Rcpp::traits::input_parameter< double >::type err(errSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(unit(eigd, U, An, lambda, Z0, V0, err, maxIter, rho));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PIE_unit", (DL_FUNC) &_PIE_unit, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_PIE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
