# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unit <- function(eigd, U, An, lambda, Z0 = NULL, V0 = NULL, err = 1e-4, maxIter = 1e3L, rho = 1) {
    .Call(`_PIE_unit`, eigd, U, An, lambda, Z0, V0, err, maxIter, rho)
}

